### ISSUE TITLE
Update Url.roc to not use Str.appendScalar

### ISSUE THREAD

**Issue by RMailaender** [roc-lang/basic-webserver#22]
[PR #6395](https://github.com/roc-lang/roc/pull/6395) removed `Str.appendScalar` from builtins. The code should be updated to user [roc-lang/unicode](https://github.com/roc-lang/unicode) instead.

**Comment by Anton-4** [comment]
roc-lang/unicode [does not have this function implemented yet](https://github.com/roc-lang/unicode/blob/3b4ec1f030fdaa339b12eec533577bb1748b6108/package/Scalar.roc#L129). I'll write up a pure Roc solution for now.

**Comment by bhansconnect** [comment]
I think we should just remove the need for `Str.appendScalar` instead of implementing it a different way.

Change `percentEncode` to accumulate to a `List U8`. Then do a single `Str.fromUtf8` that crashes on failure to parse (cause that should be impossible).

**Comment by bhansconnect** [comment]
Yeah, we should copy this from basic-cli but crash instead of using `withDefault`: https://github.com/roc-lang/basic-cli/commit/6208966e479f44457800ce593de8a38140078b1b#diff-f2522523f2f51a7e343e40fc784e44fecce8bb276db26027f3353c63f475807bR197-R228
